<?php

function shipit_json_basic_auth_handler( $user ) {
	global $wp_json_basic_auth_error;
	
	$wp_json_basic_auth_error = null;
	
	
	if ( ! empty( $user ) ) {
		return $user;
	}
	
	if ( !isset( $_SERVER['PHP_AUTH_USER'] ) ) {
		return $user;
	}
	
	$username = $_SERVER['PHP_AUTH_USER'];
	$password = $_SERVER['PHP_AUTH_PW'];
	
	
	remove_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );
	
	$user = wp_authenticate( $username, $password );
	
	add_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );
	
	if ( is_wp_error( $user ) ) {
		$wp_json_basic_auth_error = $user;
		return null;
	}
	
	$wp_json_basic_auth_error = true;
	
	return $user->ID;
}
add_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );

function shipit_json_basic_auth_error( $error ) {
	
	if ( ! empty( $error ) ) {
		return $error;
	}
	
	global $wp_json_basic_auth_error;
	
	return $wp_json_basic_auth_error;
}
add_filter( 'rest_authentication_errors', 'shipit_json_basic_auth_error' );

function comunas_de_chile($states) {
	$states['CL'] = array(
		'CL64' => "HIJUELAS",
		'CL10' => "HUARA",
		'CL36' => "ILLAPEL",
		'CL262' => "QUINCHAO",
		'CL65' => "LA CRUZ",
		'CL86' => "COLTAUCO",
		'CL89' => "LAS CABRAS",
		'CL47' => "CONCON",
		'CL37' => "CANELA",
		'CL91' => "MALLOA",
		'CL13' => "MEJILLONES",
		'CL66' => "NOGALES",
		'CL40' => "OVALLE",
		'CL11' => "PICA",
		'CL22' => "CALDERA",
		'CL50' => "QUINTERO",
		'CL15' => "TALTAL",
		'CL39' => "SALAMANCA",
		'CL45' => "VALPARAISO",
		'CL46' => "CASABLANCA",
		'CL85' => "COINCO",
		'CL82' => "VILLA ALEMANA",
		'CL61' => "ZAPALLAR",
		'CL77' => "PUTAENDO",
		'CL75' => "LLAILLAY",
		'CL59' => "PAPUDO",
		'CL338' => "ALHUE",
		'CL730' => "SOCAIRE",
		'CL4' => "GENERAL LAGOS",
		'CL758' => "VILLA PRAT",
		'CL58' => "CABILDO",
		'CL52' => "ISLA DE PASCUA",
		'CL181' => "COBQUECURA",
		'CL165' => "LOS ANGELES",
		'CL127' => "CHANCO",
		'CL168' => "LAJA",
		'CL133' => "RAUCO",
		'CL6' => "ALTO HOSPICIO",
		'CL140' => "LONGAVI",
		'CL132' => "MOLINA",
		'CL169' => "MULCHEN",
		'CL128' => "PELLUHUE",
		'CL93' => "OLIVAR",
		'CL100' => "PICHILEMU",
		'CL135' => "SAGRADA FAMILIA",
		'CL173' => "QUILLECO",
		'CL164' => "TIRUA",
		'CL98' => "REQUINOA",
		'CL161' => "CONTULMO",
		'CL129' => "CURICO",
		'CL183' => "COIHUECO",
		'CL136' => "TENO",
		'CL125' => "SAN RAFAEL",
		'CL177' => "YUMBEL",
		'CL103' => "MARCHIGUE",
		'CL102' => "LITUECHE",
		'CL160' => "CANETE",
		'CL114' => "PUMANQUE",
		'CL106' => "SAN FERNANDO",
		'CL738' => "TIGNAMAR",
		'CL19' => "TOCOPILLA",
		'CL62' => "QUILLOTA",
		'CL56' => "SAN ESTEBAN",
		'CL116' => "TALCA",
		'CL27' => "ALTO DEL CARMEN",
		'CL232' => "VALDIVIA",
		'CL199' => "YUNGAY",
		'CL202' => "CUNCO",
		'CL94' => "PEUMO",
		'CL273' => "PALENA",
		'CL162' => "CURANILAHUE",
		'CL193' => "RANQUIL",
		'CL228' => "PUREN",
		'CL197' => "SAN NICOLAS",
		'CL227' => "LUMACO",
		'CL238' => "PAILLACO",
		'CL196' => "SAN IGNACIO",
		'CL256' => "CURACO DE VELEZ",
		'CL242' => "LAGO RANCO",
		'CL236' => "MAFIL",
		'CL188' => "PEMUCO",
		'CL194' => "SAN CARLOS",
		'CL217' => "TOLTEN",
		'CL230' => "TRAIGUEN",
		'CL443' => "ARTIFICIO",
		'CL225' => "LONQUIMAY",
		'CL234' => "LANCO",
		'CL244' => "PUERTO MONTT",
		'CL222' => "COLLIPULLI",
		'CL250' => "LLANQUIHUE",
		'CL166' => "ANTUCO",
		'CL271' => "FUTALEUFU",
		'CL451' => "BELLOTO",
		'CL179' => "CHILLAN",
		'CL224' => "ERCILLA",
		'CL760' => "VILLUCO",
		'CL249' => "LOS MUERMOS",
		'CL428' => "FLORIDA",
		'CL277' => "PUERTO CISNES",
		'CL516' => "EL COLORADO",
		'CL466' => "CAMPANARIO",
		'CL283' => "RIO IBANEZ",
		'CL274' => "COYHAIQUE",
		'CL350' => "CACHAPOAL",
		'CL57' => "LA LIGUA",
		'CL366' => "CIUDAD DE LOS VALLES",
		'CL352' => "PICHIDEGUA",
		'CL364' => "BATUCO",
		'CL31' => "COQUIMBO",
		'CL180' => "BULNES",
		'CL290' => "PORVENIR",
		'CL336' => "PAINE",
		'CL285' => "LAGUNA BLANCA",
		'CL568' => "LA PLACILLA (PUNITAQUI)",
		'CL337' => "MELIPILLA",
		'CL667' => "PUAUCHO",
		'CL344' => "ISLA DE MAIPO",
		'CL435' => "TIL TIL",
		'CL292' => "TIMAUKEL",
		'CL468' => "CAPITAN PASTENE",
		'CL289' => "ANTARTICA",
		'CL363' => "RENACA",
		'CL473' => "CARIQUIMA",
		'CL761' => "VISVIRI",
		'CL281' => "TORTEL",
		'CL356' => "HORNOPIREN",
		'CL2' => "CAMARONES",
		'CL424' => "ALERCE",
		'CL167' => "CABRERO",
		'CL16' => "CALAMA",
		'CL146' => "CONCEPCION",
		'CL405' => "AYSEN",
		'CL245' => "CALBUCO",
		'CL54' => "CALLE LARGA",
		'CL72' => "SANTO DOMINGO",
		'CL410' => "ACHAO",
		'CL416' => "BATUCO (TALCA)",
		'CL385' => "CHAMPA",
		'CL399' => "CALETA BUENA",
		'CL390' => "CURIMON",
		'CL387' => "CHOCALAN",
		'CL393' => "EL MEMBRILLO",
		'CL1' => "ARICA",
		'CL398' => "POMAIRE",
		'CL406' => "LA JUNTA",
		'CL371' => "LAS VERTIENTES",
		'CL425' => "LAS CARDAS",
		'CL407' => "LLOLLEO",
		'CL414' => "PLAYA ANCHA",
		'CL376' => "MAIPO",
		'CL378' => "NOVICIADO",
		'CL381' => "SAN GABRIEL",
		'CL402' => "TONGOY",
		'CL423' => "EL CARMEN CHILLAN",
		'CL49' => "PUCHUNCAVI",
		'CL8' => "CAMINA",
		'CL334' => "BUIN",
		'CL221' => "ANGOL",
		'CL373' => "LO VALDES",
		'CL247' => "FRESIA",
		'CL148' => "CHIGUAYANTE",
		'CL279' => "COCHRANE",
		'CL139' => "COLBUN",
		'CL233' => "CORRAL",
		'CL248' => "FRUTILLAR",
		'CL203' => "CURARREHUE",
		'CL201' => "CARAHUE",
		'CL241' => "FUTRONO",
		'CL41' => "COMBARBALA",
		'CL347' => "LA CALERA",
		'CL147' => "CORONEL",
		'CL5' => "IQUIQUE",
		'CL74' => "CATEMU",
		'CL21' => "COPIAPO",
		'CL282' => "CHILE CHICO",
		'CL70' => "EL QUISCO",
		'CL204' => "FREIRE",
		'CL28' => "FREIRINA",
		'CL206' => "GORBEA",
		'CL88' => "GRANEROS",
		'CL29' => "HUASCO",
		'CL101' => "LA ESTRELLA",
		'CL33' => "LA HIGUERA",
		'CL343' => "EL MONTE",
		'CL157' => "HUALPEN",
		'CL246' => "COCHAMO",
		'CL119' => "EMPEDRADO",
		'CL220' => "CHOLCHOL",
		'CL464' => "CAMARICO",
		'CL739' => "TOCONAO",
		'CL278' => "GUAITECAS",
		'CL185' => "EL CARMEN",
		'CL87' => "DONIHUE",
		'CL429' => "OHIGGINS",
		'CL120' => "MAULE",
		'CL432' => "PALMILLA",
		'CL122' => "PENCAHUE",
		'CL345' => "PADRE HURTADO",
		'CL38' => "LOS VILOS",
		'CL158' => "LEBU",
		'CL18' => "SAN PEDRO DE ATACAMA",
		'CL263' => "OSORNO",
		'CL151' => "LOTA",
		'CL212' => "PERQUENCO",
		'CL430' => "OLLAGUE",
		'CL209' => "MELIPEUCO",
		'CL109' => "LOLOL",
		'CL121' => "PELARCO",
		'CL81' => "OLMUE",
		'CL112' => "PERALILLO",
		'CL237' => "MARIQUINA",
		'CL84' => "CODEGUA",
		'CL76' => "PANQUEHUE",
		'CL431' => "PAIHUANO",
		'CL226' => "LOS SAUCES",
		'CL171' => "NEGRETE",
		'CL187' => "NIQUEN",
		'CL331' => "LAMPA",
		'CL163' => "LOS ALAMOS",
		'CL80' => "LIMACHE",
		'CL219' => "VILLARRICA",
		'CL53' => "LOS ANDES",
		'CL340' => "MARIA PINTO",
		'CL620' => "MEHUIN",
		'CL141' => "PARRAL",
		'CL258' => "PUQUELDON",
		'CL286' => "RIO VERDE",
		'CL418' => "PLACILLA (VINA DEL MAR)",
		'CL214' => "PUCON",
		'CL97' => "RENGO",
		'CL265' => "PURRANQUE",
		'CL215' => "SAAVEDRA",
		'CL205' => "GALVARINO",
		'CL268' => "SAN JUAN DE LA COSTA",
		'CL83' => "RANCAGUA",
		'CL124' => "SAN CLEMENTE",
		'CL67' => "SAN ANTONIO",
		'CL7' => "POZO ALMONTE",
		'CL143' => "SAN JAVIER",
		'CL634' => "NELTUME",
		'CL71' => "EL TABO",
		'CL287' => "SAN GREGORIO",
		'CL182' => "COELEMU",
		'CL44' => "RIO HURTADO",
		'CL3' => "PUTRE",
		'CL433' => "SAN PEDRO DE MELIPILLA",
		'CL229' => "RENAICO",
		'CL154' => "SANTA JUANA",
		'CL517' => "EL HINOJAL",
		'CL539' => "GUARDIA VIEJA",
		'CL73' => "SAN FELIPE",
		'CL765' => "BARROS ARANA",
		'CL113' => "PLACILLA",
		'CL142' => "RETIRO",
		'CL78' => "SANTA MARIA",
		'CL55' => "RINCONADA",
		'CL12' => "ANTOFAGASTA",
		'CL191' => "QUILLON",
		'CL200' => "TEMUCO",
		'CL131' => "LICANTEN",
		'CL445' => "BAHIA MANSA",
		'CL26' => "VALLENAR",
		'CL444' => "BAHIA INGLESA",
		'CL463' => "CALETONES",
		'CL447' => "BALMACEDA",
		'CL450' => "BELEN",
		'CL178' => "ALTO BIOBIO",
		'CL452' => "BOBADILLA",
		'CL156' => "TOME",
		'CL453' => "BUCALEMU",
		'CL455' => "CABURGA",
		'CL454' => "BUCHUPUREO",
		'CL457' => "CAHUIL",
		'CL459' => "CAJON",
		'CL400' => "ANCUAQUE",
		'CL460' => "CALAFQUEN",
		'CL462' => "CALETA GONZALO",
		'CL461' => "CALETA ANDRADE",
		'CL465' => "CAMERON",
		'CL145' => "YERBAS BUENAS",
		'CL449' => "BARRANCAS",
		'CL137' => "VICHUQUEN",
		'CL35' => "VICUNA",
		'CL384' => "BOLLENAR",
		'CL437' => "AHUI",
		'CL438' => "AIQUINA",
		'CL439' => "ALGARROBAL",
		'CL294' => "TORRES DEL PAINE",
		'CL446' => "BAHIA MURTA",
		'CL150' => "HUALQUI",
		'CL441' => "ALICAHUE",
		'CL448' => "BAQUEDANO",
		'CL130' => "HUALANE",
		'CL492' => "COBIJA",
		'CL388' => "CODIGUA",
		'CL494' => "CODPA",
		'CL472' => "CAREN",
		'CL496' => "COLIUMO",
		'CL152' => "PENCO",
		'CL469' => "CAQUENA",
		'CL497' => "COLLACAGUA",
		'CL499' => "CONAY",
		'CL500' => "COSAPILLA",
		'CL501' => "COYA",
		'CL503' => "CULENAR",
		'CL504' => "CUMPEO",
		'CL505' => "CUNACO",
		'CL506' => "CUNCUMEN",
		'CL508' => "CURINANCO",
		'CL510' => "DEGAN",
		'CL511' => "DICHATO",
		'CL509' => "CUYA",
		'CL513' => "DUAO",
		'CL391' => "EL CANELO",
		'CL470' => "CARAMPANGUE",
		'CL471' => "CARELMAPU",
		'CL386' => "CHICUREO",
		'CL401' => "CANCOSA",
		'CL482' => "CHANARAL ALTO",
		'CL483' => "CHANARAL DE CAREN",
		'CL486' => "CHEPU",
		'CL412' => "CURAUMA",
		'CL487' => "CHERCHENCO",
		'CL467' => "CANTO DE AGUA",
		'CL484' => "CHARRUA",
		'CL562' => "LA HAUYCA",
		'CL488' => "CHILLEPIN",
		'CL485' => "CHAUQUEN",
		'CL174' => "SAN ROSENDO",
		'CL529' => "ENTRE LAGOS",
		'CL530' => "ESQUINA",
		'CL524' => "EL SAUCE",
		'CL176' => "TUCAPEL",
		'CL532' => "FARELLONES",
		'CL534' => "GUADAL",
		'CL535' => "GUALLECO",
		'CL552' => "HUINTIL",
		'CL538' => "GUAPILACUY",
		'CL541' => "HORCON",
		'CL542' => "HORCON IV",
		'CL518' => "EL MANZANO",
		'CL550' => "HUEPIL",
		'CL544' => "HOSPITAL",
		'CL545' => "HUALPENCILLO",
		'CL547' => "HUELDEN",
		'CL548' => "HUELLAHUE",
		'CL551' => "HUILLINCO",
		'CL553' => "ICALMA",
		'CL554' => "ILOCA",
		'CL521' => "EL PAICO",
		'CL556' => "ISLA TEJA",
		'CL557' => "ISLUGA",
		'CL536' => "GUANAQUEROS",
		'CL561' => "LA CHIMBA",
		'CL558' => "ITAHUE",
		'CL368' => "EL INGENIO",
		'CL563' => "LA JARILLA",
		'CL564' => "LA MARQUESA",
		'CL565' => "LA NEGRA",
		'CL566' => "LA OBRA",
		'CL559' => "LA ARENA",
		'CL523' => "EL PENON",
		'CL525' => "EL TABITO",
		'CL115' => "SANTA CRUZ",
		'CL579' => "LAS CRUCES",
		'CL581' => "LAS DUNAS",
		'CL573' => "LAGUNA VERDE",
		'CL584' => "LAS TACAS",
		'CL585' => "LAS TRANCAS",
		'CL24' => "CHANARAL",
		'CL587' => "LASANA",
		'CL588' => "LECHAGUA",
		'CL589' => "LEYDA",
		'CL590' => "LICANRAY",
		'CL591' => "LIMARI",
		'CL592' => "LINAO",
		'CL594' => "LIRIMA",
		'CL595' => "LIRQUEN",
		'CL396' => "LO CHACON",
		'CL597' => "LLICO",
		'CL599' => "LO MIRANDA",
		'CL570' => "LA TAPERA",
		'CL600' => "LO VALDIVIA",
		'CL603' => "LOS HORCONES",
		'CL604' => "LOS HORNOS",
		'CL576' => "LARAQUETE",
		'CL605' => "LOS LAURELES",
		'CL608' => "LOS MOLLES",
		'CL609' => "LOS NICHES",
		'CL610' => "LOS OLIVOS",
		'CL611' => "MAICOLPUE",
		'CL645' => "PAN DE AZUCAR",
		'CL614' => "MANAO",
		'CL370' => "LAGUNA ACULEO",
		'CL582' => "LAS NIEVES",
		'CL571' => "LA TIRANA",
		'CL426' => "LAS CARDAS SUR",
		'CL372' => "LINDEROS",
		'CL186' => "NINHUE",
		'CL628' => "MONTE AYMOND",
		'CL629' => "MONTE GRANDE",
		'CL631' => "MORRILLOS",
		'CL636' => "NIPAS",
		'CL638' => "NIRIVILO",
		'CL615' => "MANDINGA",
		'CL640' => "NUEVA BRAUNAU",
		'CL641' => "PACHAMA",
		'CL643' => "PALOMAR",
		'CL642' => "PAIPOTE",
		'CL646' => "PANGAL",
		'CL647' => "PANIMAVIDA",
		'CL648' => "PAPOSO",
		'CL621' => "MELINKA",
		'CL650' => "PARGUA",
		'CL651' => "PAULDEO",
		'CL652' => "PEDREGAL",
		'CL654' => "PENABLANCA",
		'CL655' => "PETROHUE",
		'CL656' => "PICHASCA",
		'CL657' => "PICHI PELLUCO",
		'CL658' => "PICHICUY",
		'CL661' => "PINGUERAL",
		'CL662' => "PISCO ELQUI",
		'CL663' => "POCONCHILE",
		'CL618' => "MATANZAS",
		'CL664' => "POLCURA",
		'CL644' => "PALQUIAL",
		'CL622' => "MINAS DEL PRADO",
		'CL635' => "NIEBLA",
		'CL380' => "NOS",
		'CL625' => "MOCHA",
		'CL189' => "PINTO",
		'CL383' => "ALTO JAHUEL",
		'CL672' => "PUENTE QUILO",
		'CL714' => "ROSARIO",
		'CL676' => "PUERTO BERTRAND",
		'CL675' => "PUERTO ALDEA",
		'CL671' => "PUENTE NEGRO",
		'CL240' => "LA UNION",
		'CL673' => "PUERTECILLO",
		'CL522' => "EL PALQUI",
		'CL682' => "PUERTO WILLIAMS",
		'CL677' => "PUERTO BORIES",
		'CL679' => "PUERTO TORO",
		'CL716' => "RUCAPEQUEN",
		'CL705' => "RAPEL",
		'CL669' => "PUEBLO SECO",
		'CL706' => "RAYENCURA",
		'CL668' => "PUCATRIHUE",
		'CL713' => "ROBLE HUACHO",
		'CL707' => "RECOLETA IV",
		'CL708' => "RIHUE",
		'CL709' => "RINCONADA DE GUZMAN",
		'CL710' => "RINCONADA DE SILVA",
		'CL711' => "RINIHUE",
		'CL218' => "VILCUN",
		'CL68' => "ALGARROBO",
		'CL107' => "CHEPICA",
		'CL190' => "PORTEZUELO",
		'CL392' => "EL MELOCOTON",
		'CL192' => "QUIRIHUE",
		'CL759' => "VILLA SANTA LUCIA",
		'CL369' => "HUELQUEN",
		'CL377' => "MALLOCO",
		'CL159' => "ARAUCO",
		'CL575' => "LAJAS BLANCAS",
		'CL724' => "SAN PEDRO QUINTA REGION",
		'CL731' => "SOCOROMA",
		'CL408' => "SOTOCA",
		'CL763' => "ZEMITA",
		'CL733' => "SORA",
		'CL734' => "SOTAQUI",
		'CL404' => "NAVIDAD",
		'CL48' => "JUAN FERNANDEZ",
		'CL756' => "VILLA MERCEDES",
		'CL270' => "CHAITEN",
		'CL719' => "SAN JUAN",
		'CL735' => "TAMBILLO",
		'CL737' => "TIERRAS BLANCAS",
		'CL736' => "TANILVORO",
		'CL342' => "TALAGANTE",
		'CL434' => "SAN VICENTE DE TAGUA TAGUA",
		'CL198' => "TREGUACO",
		'CL375' => "LONQUEN",
		'CL172' => "QUILACO",
		'CL117' => "CONSTITUCION",
		'CL118' => "CUREPTO",
		'CL69' => "CARTAGENA",
		'CL108' => "CHIMBARONGO",
		'CL207' => "LAUTARO",
		'CL239' => "PANGUIPULLI",
		'CL329' => "SAN JOSE DE MAIPO",
		'CL264' => "PUERTO OCTAY",
		'CL155' => "TALCAHUANO",
		'CL23' => "TIERRA AMARILLA",
		'CL440' => "ALGARROBITO",
		'CL722' => "SAN MARCOS",
		'CL293' => "PUERTO NATALES",
		'CL79' => "QUILPUE",
		'CL138' => "LINARES",
		'CL25' => "DIEGO DE ALMAGRO",
		'CL310' => "LO ESPEJO",
		'CL318' => "PUDAHUEL",
		'CL740' => "TOPOCALMA",
		'CL208' => "LONCOCHE",
		'CL90' => "MACHALI",
		'CL389' => "CULIPRAN",
		'CL269' => "SAN PABLO",
		'CL572' => "LABRANZA",
		'CL367' => "ALTO EL CANELO",
		'CL490' => "CHOSHUENCO",
		'CL491' => "CIRUELOS",
		'CL110' => "NANCAGUA",
		'CL259' => "QUEILEN",
		'CL9' => "COLCHANE",
		'CL243' => "RIO BUENO",
		'CL105' => "PAREDONES",
		'CL479' => "CERRILLOS DE TAMAYA",
		'CL272' => "HUALAIHUE",
		'CL309' => "LO BARNECHEA",
		'CL507' => "CURANIPE",
		'CL481' => "CHACAO",
		'CL20' => "MARIA ELENA",
		'CL235' => "LOS LAGOS",
		'CL92' => "MOSTAZAL",
		'CL498' => "CONARIPE",
		'CL42' => "MONTE PATRIA",
		'CL549' => "HUENTELAUQUEN",
		'CL531' => "ESTACION PAIPOTE",
		'CL543' => "HORNITOS",
		'CL346' => "PENAFLOR",
		'CL330' => "COLINA",
		'CL255' => "CHONCHI",
		'CL660' => "PILLANLELBUN",
		'CL413' => "PUERTO CHACABUCO",
		'CL379' => "RUNGUE",
		'CL60' => "PETORCA",
		'CL267' => "RIO NEGRO",
		'CL134' => "ROMERAL",
		'CL723' => "SAN PEDRO DE ALCANTARA",
		'CL354' => "SAN FRANCISCO DE MOSTAZAL",
		'CL254' => "ANCUD",
		'CL252' => "PUERTO VARAS",
		'CL253' => "CASTRO",
		'CL175' => "SANTA BARBARA",
		'CL260' => "QUELLON",
		'CL701' => "QUIRIQUINA",
		'CL477' => "CAULIN",
		'CL96' => "QUINTA DE TILCOCO",
		'CL520' => "EL MOLLE",
		'CL526' => "EL TAMBO",
		'CL284' => "PUNTA ARENAS",
		'CL567' => "LA PARVA",
		'CL442' => "ALTOVALSOL",
		'CL476' => "CATAPILCO",
		'CL480' => "CERRO SOMBRERO",
		'CL665' => "POPETA",
		'CL519' => "EL MELON",
		'CL475' => "CASPANA",
		'CL394' => "GUAYACAN",
		'CL578' => "LAS BREAS",
		'CL580' => "LAS DICHAS",
		'CL593' => "LIQUINE",
		'CL601' => "LONGOVILO",
		'CL51' => "VINA DEL MAR",
		'CL365' => "CAJON DEL MAIPO",
		'CL436' => "AGUA BUENA",
		'CL456' => "CACHAGUA",
		'CL489' => "CHOLGUAN",
		'CL495' => "COIHUE",
		'CL502' => "COZ COZ",
		'CL515' => "EL CARMEN RENGO",
		'CL514' => "EL BELLOTO",
		'CL528' => "ENSENADA",
		'CL533' => "GABRIELA MISTRAL",
		'CL546' => "HUAMALATA",
		'CL560' => "LA CEBADA",
		'CL474' => "CARRIZAL BAJO",
		'CL574' => "LAGUNILLAS",
		'CL586' => "LAS VENTANAS",
		'CL598' => "LLIFEN",
		'CL607' => "LOS MAITENES",
		'CL602' => "LONTUE",
		'CL627' => "MONTE AGUILA",
		'CL632' => "NAHUELTORO",
		'CL649' => "PARCELA EL CARMEN",
		'CL659' => "PICHIDANGUI",
		'CL637' => "NIREHUAO",
		'CL712' => "RININAHUE",
		'CL732' => "SOCOS",
		'CL170' => "NACIMIENTO",
		'CL382' => "VALDIVIA DE PAINE",
		'CL216' => "TEODORO SCHMIDT",
		'CL596' => "LLANOS DE GUANTA",
		'CL527' => "EL TANGUE",
		'CL613' => "MAMINA",
		'CL144' => "VILLA ALEGRE",
		'CL32' => "ANDACOLLO",
		'CL537' => "GUANGUALI",
		'CL577' => "LARMAHUE",
		'CL749' => "VALLE NEVADO",
		'CL721' => "SAN MANUEL",
		'CL751' => "VEGAS DE ITATA",
		'CL750' => "VALLE SIMPSON",
		'CL752' => "VILLA ALHUE",
		'CL754' => "VILLA CERRO CASTILLO",
		'CL755' => "VILLA MANIHUALES",
		'CL757' => "VILLA ORTEGA",
		'CL626' => "MOLINOS",
		'CL630' => "MONTENEGRO",
		'CL653' => "PELEQUEN",
		'CL741' => "TOTORALILLO",
		'CL307' => "LA REINA",
		'CL266' => "PUYEHUE",
		'CL421' => "MAITENCILLO",
		'CL678' => "PUERTO DOMINGUEZ",
		'CL688' => "PUNTA LAVAPIE",
		'CL697' => "QUILIMARI",
		'CL747' => "TUBUL",
		'CL195' => "SAN FABIAN",
		'CL153' => "SAN PEDRO DE LA PAZ",
		'CL569' => "LA RUFINA",
		'CL261' => "QUEMCHI",
		'CL257' => "DALCAHUE",
		'CL184' => "CHILLAN VIEJO",
		'CL753' => "VILLA AMENGUAL",
		'CL715' => "RUCA RAQUI (SAAVEDRA)",
		'CL123' => "RIO CLARO",
		'CL251' => "MAULLIN",
		'CL14' => "SIERRA GORDA",
		'CL764' => "FUERTE BAQUEDANO",
		'CL126' => "CAUQUENES",
		'CL317' => "PROVIDENCIA",
		'CL211' => "PADRE LAS CASAS",
		'CL328' => "PIRQUE",
		'CL623' => "MINCHA",
		'CL624' => "MININCO",
		'CL327' => "PUENTE ALTO",
		'CL326' => "VITACURA",
		'CL296' => "CERRILLOS",
		'CL339' => "CURACAVI",
		'CL291' => "PRIMAVERA",
		'CL478' => "CAYUCUPIL",
		'CL606' => "LOS LINGUES",
		'CL639' => "NUEVA ALDEA",
		'CL699' => "QUINCHAMALI",
		'CL633' => "NAL",
		'CL616' => "MARBELLA",
		'CL357' => "OLIVAR ALTO",
		'CL619' => "MECHAICO",
		'CL397' => "POLPAICO",
		'CL690' => "PUYUHUAPI",
		'CL680' => "PUERTO TRANQUILO",
		'CL681' => "PUERTO VELERO",
		'CL684' => "PUNTA CORONA",
		'CL666' => "PORTILLO",
		'CL683' => "PUNTA COLORADA",
		'CL692' => "QUELON",
		'CL685' => "PUNTA DE PARRA",
		'CL686' => "PUNTA DE TRALCA",
		'CL687' => "PUNTA DELGADA",
		'CL689' => "PUNUCAPA",
		'CL728' => "SECTOR LA PENA",
		'CL691' => "QUEBRADA DE TALCA",
		'CL693' => "QUEPE",
		'CL670' => "PUELO",
		'CL694' => "QUETALMAHUE",
		'CL319' => "QUILICURA",
		'CL695' => "QUEULE",
		'CL696' => "QUILCHE",
		'CL698' => "QUILLAGUA",
		'CL700' => "QUINTAY",
		'CL702' => "RAFAEL",
		'CL703' => "RAMADILLAS",
		'CL704' => "RANGUELMO",
		'CL725' => "SAN SEBASTIAN",
		'CL726' => "SANTA CLARA",
		'CL275' => "LAGO VERDE",
		'CL727' => "SANTA ROSA DE CHENA",
		'CL729' => "SEWELL",
		'CL555' => "ISLA NEGRA",
		'CL674' => "PUERTO AGUIRRE",
		'CL742' => "TREGUALEMU",
		'CL743' => "TREHUACO",
		'CL744' => "TROVOLHUE",
		'CL745' => "TRUMAO",
		'CL717' => "SALADILLO",
		'CL746' => "TRUPAN",
		'CL748' => "TULAHUEN",
		'CL720' => "SAN JULIAN",
		'CL718' => "SAN ALFONSO",
		'CL762' => "YUSTE",
		'CL223' => "CURACAUTIN",
		'CL231' => "VICTORIA",
		'CL348' => "EL SALVADOR",
		'CL374' => "LOMAS DE LO AGUIRRE",
		'CL493' => "CODELCO RADOMIRO TOMIC",
		'CL512' => "DOMEYKO",
		'CL540' => "HACIENDA LOS ANDES",
		'CL30' => "LA SERENA",
		'CL395' => "JUNCAL",
		'CL612' => "MALALCAHUELLO",
		'CL417' => "RAUQUEN",
		'CL335' => "CALERA DE TANGO",
		'CL210' => "NUEVA IMPERIAL",
		'CL213' => "PITRUFQUEN",
		'CL43' => "PUNITAQUI",
		'CL458' => "CAIMANES",
		'CL583' => "LAS RAMADAS DE TULAHUEN",
		'CL427' => "CABO DE HORNOS",
		'CL314' => "NUNOA",
		'CL324' => "SAN MIGUEL",
		'CL312' => "MACUL",
		'CL315' => "PEDRO AGUIRRE CERDA",
		'CL333' => "SAN BERNARDO",
		'CL316' => "PENALOLEN",
		'CL304' => "LA FLORIDA",
		'CL298' => "CONCHALI",
		'CL302' => "INDEPENDENCIA",
		'CL299' => "EL BOSQUE",
		'CL323' => "SAN JOAQUIN",
		'CL321' => "RECOLETA",
		'CL320' => "QUINTA NORMAL",
		'CL297' => "CERRO NAVIA",
		'CL322' => "RENCA",
		'CL305' => "LA GRANJA",
		'CL300' => "ESTACION CENTRAL",
		'CL306' => "LA PINTANA",
		'CL325' => "SAN RAMON",
		'CL301' => "HUECHURABA",
		'CL311' => "LO PRADO",
		'CL313' => "MAIPU",
		'CL303' => "LA CISTERNA",
		'CL308' => "LAS CONDES",
		'CL295' => "SANTIAGO CENTRO",
	);
	
	return $states;
}

function cambio_campos_checkout( $fields ) {
	
	unset($fields['billing']['billing_postcode']);
	unset($fields['shipping']['shipping_postcode']);
	
	$fields['billing']['billing_state']['label']= 'Comunas'; 
	$fields['shipping']['shipping_state']['label']= 'Comunas'; 
	
	$fields['billing']['billing_address_1']['class'] = array('form-row-first');
	$fields['shipping']['shipping_address_1']['class'] = array('form-row-first');      
	
	return $fields;
}
function shipit_woocommerce_tip(){
	?>
	<script type="text/javascript">
	jQuery( document ).ready(function( $ ) {
		jQuery('label[for="billing_state"]').text('Comunas');
		$('#billing_state').change(function(){
			jQuery('body').trigger('update_checkout');
		});
	});
	</script>
	<?php
}
add_filter( 'woocommerce_order_formatted_billing_address' , 'shipit_admin_default_billing_address_fields', 10, 2 );
 
function shipit_admin_default_billing_address_fields( $fields, $order ) {
$fields['billing_houseno'] = get_post_meta( $order->get_id(), '_billing_houseno', true );
return $fields;
}
add_filter( 'woocommerce_order_formatted_shipping_address' , 'shipit_admin_default_shipping_address_fields', 10, 2 );
 
function shipit_admin_default_shipping_address_fields( $fields, $order ) {
$fields['shipping_houseno'] = get_post_meta( $order->get_id(), '_shipping_houseno', true );
return $fields;
}
add_filter( 'woocommerce_formatted_address_replacements', 'shipit_add_new_replacement_fields',10,2 );
 
function shipit_add_new_replacement_fields( $replacements, $address ) {
$replacements['{billing_houseno}'] = isset($address['billing_houseno']) ? $address['billing_houseno'] : '';
$replacements['{shipping_houseno}'] = isset($address['shipping_houseno']) ? $address['shipping_houseno'] : '';
return $replacements;
}
add_filter( 'woocommerce_localisation_address_formats', 'shipit_admin_new_address_formats' );
 
function shipit_admin_new_address_formats( $formats ) {
$formats['CL'] = "{name_upper}\n{company_upper}\n{address_1_upper}\n{billing_houseno}\n{shipping_houseno}\n{address_2_upper}\n{city_upper}\n{state_upper}\n{postcode_upper}\n{country}";
return $formats;
}

function shipit_houseno_display_order_data_in_admin( $order ){  ?>
    <div class="order_data_column">

        <h4><?php _e( 'Campos Shipit', 'woocommerce' ); ?><a href="#" class="edit_address"><?php _e( 'Edit', 'woocommerce' ); ?></a></h4>
        <div class="address">
        <?php 
            echo '<p><strong>' . __( 'Numero de vivienda Facturacion' ) . ':</strong>' . $order->get_meta( '_billing_houseno' ) . '</p>';
            echo '<p><strong>' . __( 'Numero de vivienda Envio' ) . ':</strong>' . $order->get_meta( '_shipping_houseno' ) . '</p>'; ?>
        </div>
        <div class="edit_address">
            <?php woocommerce_wp_text_input( array( 'id' => '_billing_houseno', 'label' => __( 'Numero de vivienda' ), 'wrapper_class' => '_billing_houseno' ) ); ?>
            <?php woocommerce_wp_text_input( array( 'id' => '_shipping_houseno', 'label' => __( 'Numero de vivienda Envio' ), 'wrapper_class' => '_shipping_houseno' ) ); ?>
        </div>
    </div>
<?php }
add_action( 'woocommerce_admin_order_data_after_order_details', 'shipit_houseno_display_order_data_in_admin' );

function shipit_houseno_save_extra_details( $order_id, $post ){
    $order = wc_get_order( $order_id );
    $order->update_meta_data( '_billing_houseno', wc_clean( $_POST[ '_billing_houseno' ] ) );
    $order->update_meta_data( '_shipping_houseno', wc_clean( $_POST[ '_shipping_houseno' ] ) );
    $order->save_meta_data();
}
add_action( 'woocommerce_process_shop_order_meta', 'shipit_houseno_save_extra_details', 45, 2 );

add_action( 'wp_head', 'shipit_woocommerce_tip' );
add_filter('woocommerce_checkout_fields' , 'cambio_campos_checkout');
add_filter('woocommerce_states', 'comunas_de_chile');
?>