<?php

function shipit_json_basic_auth_handler( $user ) {
	global $wp_json_basic_auth_error;
	
	$wp_json_basic_auth_error = null;
	
	
	if ( ! empty( $user ) ) {
		return $user;
	}
	
	if ( !isset( $_SERVER['PHP_AUTH_USER'] ) ) {
		return $user;
	}
	
	$username = $_SERVER['PHP_AUTH_USER'];
	$password = $_SERVER['PHP_AUTH_PW'];
	
	
	remove_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );
	
	$user = wp_authenticate( $username, $password );
	
	add_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );
	
	if ( is_wp_error( $user ) ) {
		$wp_json_basic_auth_error = $user;
		return null;
	}
	
	$wp_json_basic_auth_error = true;
	
	return $user->ID;
}
add_filter( 'determine_current_user', 'shipit_json_basic_auth_handler', 20 );

function shipit_json_basic_auth_error( $error ) {
	
	if ( ! empty( $error ) ) {
		return $error;
	}
	
	global $wp_json_basic_auth_error;
	
	return $wp_json_basic_auth_error;
}
add_filter( 'rest_authentication_errors', 'shipit_json_basic_auth_error' );

function comunas_de_chile($states) {
	$states['CL'] = array(
		'64' => "HIJUELAS",
		'10' => "HUARA",
		'36' => "ILLAPEL",
		'262' => "QUINCHAO",
		'65' => "LA CRUZ",
		'86' => "COLTAUCO",
		'89' => "LAS CABRAS",
		'47' => "CONCON",
		'37' => "CANELA",
		'91' => "MALLOA",
		'13' => "MEJILLONES",
		'66' => "NOGALES",
		'40' => "OVALLE",
		'11' => "PICA",
		'22' => "CALDERA",
		'50' => "QUINTERO",
		'15' => "TALTAL",
		'39' => "SALAMANCA",
		'45' => "VALPARAISO",
		'46' => "CASABLANCA",
		'85' => "COINCO",
		'82' => "VILLA ALEMANA",
		'61' => "ZAPALLAR",
		'77' => "PUTAENDO",
		'75' => "LLAILLAY",
		'59' => "PAPUDO",
		'338' => "ALHUE",
		'730' => "SOCAIRE",
		'4' => "GENERAL LAGOS",
		'758' => "VILLA PRAT",
		'58' => "CABILDO",
		'52' => "ISLA DE PASCUA",
		'181' => "COBQUECURA",
		'165' => "LOS ANGELES",
		'127' => "CHANCO",
		'168' => "LAJA",
		'133' => "RAUCO",
		'6' => "ALTO HOSPICIO",
		'140' => "LONGAVI",
		'132' => "MOLINA",
		'169' => "MULCHEN",
		'128' => "PELLUHUE",
		'93' => "OLIVAR",
		'100' => "PICHILEMU",
		'135' => "SAGRADA FAMILIA",
		'173' => "QUILLECO",
		'164' => "TIRUA",
		'98' => "REQUINOA",
		'161' => "CONTULMO",
		'129' => "CURICO",
		'183' => "COIHUECO",
		'136' => "TENO",
		'125' => "SAN RAFAEL",
		'177' => "YUMBEL",
		'103' => "MARCHIGUE",
		'102' => "LITUECHE",
		'160' => "CANETE",
		'114' => "PUMANQUE",
		'106' => "SAN FERNANDO",
		'738' => "TIGNAMAR",
		'19' => "TOCOPILLA",
		'62' => "QUILLOTA",
		'56' => "SAN ESTEBAN",
		'116' => "TALCA",
		'27' => "ALTO DEL CARMEN",
		'232' => "VALDIVIA",
		'199' => "YUNGAY",
		'202' => "CUNCO",
		'94' => "PEUMO",
		'273' => "PALENA",
		'162' => "CURANILAHUE",
		'193' => "RANQUIL",
		'228' => "PUREN",
		'197' => "SAN NICOLAS",
		'227' => "LUMACO",
		'238' => "PAILLACO",
		'196' => "SAN IGNACIO",
		'256' => "CURACO DE VELEZ",
		'242' => "LAGO RANCO",
		'236' => "MAFIL",
		'188' => "PEMUCO",
		'194' => "SAN CARLOS",
		'217' => "TOLTEN",
		'230' => "TRAIGUEN",
		'443' => "ARTIFICIO",
		'225' => "LONQUIMAY",
		'234' => "LANCO",
		'244' => "PUERTO MONTT",
		'222' => "COLLIPULLI",
		'250' => "LLANQUIHUE",
		'166' => "ANTUCO",
		'271' => "FUTALEUFU",
		'451' => "BELLOTO",
		'179' => "CHILLAN",
		'224' => "ERCILLA",
		'760' => "VILLUCO",
		'249' => "LOS MUERMOS",
		'428' => "FLORIDA",
		'277' => "PUERTO CISNES",
		'516' => "EL COLORADO",
		'466' => "CAMPANARIO",
		'283' => "RIO IBANEZ",
		'274' => "COYHAIQUE",
		'350' => "CACHAPOAL",
		'57' => "LA LIGUA",
		'366' => "CIUDAD DE LOS VALLES",
		'352' => "PICHIDEGUA",
		'364' => "BATUCO",
		'31' => "COQUIMBO",
		'180' => "BULNES",
		'290' => "PORVENIR",
		'336' => "PAINE",
		'285' => "LAGUNA BLANCA",
		'568' => "LA PLACILLA (PUNITAQUI)",
		'337' => "MELIPILLA",
		'667' => "PUAUCHO",
		'344' => "ISLA DE MAIPO",
		'435' => "TIL TIL",
		'292' => "TIMAUKEL",
		'468' => "CAPITAN PASTENE",
		'289' => "ANTARTICA",
		'363' => "RENACA",
		'473' => "CARIQUIMA",
		'761' => "VISVIRI",
		'281' => "TORTEL",
		'356' => "HORNOPIREN",
		'2' => "CAMARONES",
		'424' => "ALERCE",
		'167' => "CABRERO",
		'16' => "CALAMA",
		'146' => "CONCEPCION",
		'405' => "AYSEN",
		'245' => "CALBUCO",
		'54' => "CALLE LARGA",
		'72' => "SANTO DOMINGO",
		'410' => "ACHAO",
		'416' => "BATUCO (TALCA)",
		'385' => "CHAMPA",
		'399' => "CALETA BUENA",
		'390' => "CURIMON",
		'387' => "CHOCALAN",
		'393' => "EL MEMBRILLO",
		'1' => "ARICA",
		'398' => "POMAIRE",
		'406' => "LA JUNTA",
		'371' => "LAS VERTIENTES",
		'425' => "LAS CARDAS",
		'407' => "LLOLLEO",
		'414' => "PLAYA ANCHA",
		'376' => "MAIPO",
		'378' => "NOVICIADO",
		'381' => "SAN GABRIEL",
		'402' => "TONGOY",
		'423' => "EL CARMEN CHILLAN",
		'49' => "PUCHUNCAVI",
		'8' => "CAMINA",
		'334' => "BUIN",
		'221' => "ANGOL",
		'373' => "LO VALDES",
		'247' => "FRESIA",
		'148' => "CHIGUAYANTE",
		'279' => "COCHRANE",
		'139' => "COLBUN",
		'233' => "CORRAL",
		'248' => "FRUTILLAR",
		'203' => "CURARREHUE",
		'201' => "CARAHUE",
		'241' => "FUTRONO",
		'41' => "COMBARBALA",
		'347' => "LA CALERA",
		'147' => "CORONEL",
		'5' => "IQUIQUE",
		'74' => "CATEMU",
		'21' => "COPIAPO",
		'282' => "CHILE CHICO",
		'70' => "EL QUISCO",
		'204' => "FREIRE",
		'28' => "FREIRINA",
		'206' => "GORBEA",
		'88' => "GRANEROS",
		'29' => "HUASCO",
		'101' => "LA ESTRELLA",
		'33' => "LA HIGUERA",
		'343' => "EL MONTE",
		'157' => "HUALPEN",
		'246' => "COCHAMO",
		'119' => "EMPEDRADO",
		'220' => "CHOLCHOL",
		'464' => "CAMARICO",
		'739' => "TOCONAO",
		'278' => "GUAITECAS",
		'185' => "EL CARMEN",
		'87' => "DONIHUE",
		'429' => "OHIGGINS",
		'120' => "MAULE",
		'432' => "PALMILLA",
		'122' => "PENCAHUE",
		'345' => "PADRE HURTADO",
		'38' => "LOS VILOS",
		'158' => "LEBU",
		'18' => "SAN PEDRO DE ATACAMA",
		'263' => "OSORNO",
		'151' => "LOTA",
		'212' => "PERQUENCO",
		'430' => "OLLAGUE",
		'209' => "MELIPEUCO",
		'109' => "LOLOL",
		'121' => "PELARCO",
		'81' => "OLMUE",
		'112' => "PERALILLO",
		'237' => "MARIQUINA",
		'84' => "CODEGUA",
		'76' => "PANQUEHUE",
		'431' => "PAIHUANO",
		'226' => "LOS SAUCES",
		'171' => "NEGRETE",
		'187' => "NIQUEN",
		'331' => "LAMPA",
		'163' => "LOS ALAMOS",
		'80' => "LIMACHE",
		'219' => "VILLARRICA",
		'53' => "LOS ANDES",
		'340' => "MARIA PINTO",
		'620' => "MEHUIN",
		'141' => "PARRAL",
		'258' => "PUQUELDON",
		'286' => "RIO VERDE",
		'418' => "PLACILLA (VINA DEL MAR)",
		'214' => "PUCON",
		'97' => "RENGO",
		'265' => "PURRANQUE",
		'215' => "SAAVEDRA",
		'205' => "GALVARINO",
		'268' => "SAN JUAN DE LA COSTA",
		'83' => "RANCAGUA",
		'124' => "SAN CLEMENTE",
		'67' => "SAN ANTONIO",
		'7' => "POZO ALMONTE",
		'143' => "SAN JAVIER",
		'634' => "NELTUME",
		'71' => "EL TABO",
		'287' => "SAN GREGORIO",
		'182' => "COELEMU",
		'44' => "RIO HURTADO",
		'3' => "PUTRE",
		'433' => "SAN PEDRO DE MELIPILLA",
		'229' => "RENAICO",
		'154' => "SANTA JUANA",
		'517' => "EL HINOJAL",
		'539' => "GUARDIA VIEJA",
		'73' => "SAN FELIPE",
		'765' => "BARROS ARANA",
		'113' => "PLACILLA",
		'142' => "RETIRO",
		'78' => "SANTA MARIA",
		'55' => "RINCONADA",
		'12' => "ANTOFAGASTA",
		'191' => "QUILLON",
		'200' => "TEMUCO",
		'131' => "LICANTEN",
		'445' => "BAHIA MANSA",
		'26' => "VALLENAR",
		'444' => "BAHIA INGLESA",
		'463' => "CALETONES",
		'447' => "BALMACEDA",
		'450' => "BELEN",
		'178' => "ALTO BIOBIO",
		'452' => "BOBADILLA",
		'156' => "TOME",
		'453' => "BUCALEMU",
		'455' => "CABURGA",
		'454' => "BUCHUPUREO",
		'457' => "CAHUIL",
		'459' => "CAJON",
		'400' => "ANCUAQUE",
		'460' => "CALAFQUEN",
		'462' => "CALETA GONZALO",
		'461' => "CALETA ANDRADE",
		'465' => "CAMERON",
		'145' => "YERBAS BUENAS",
		'449' => "BARRANCAS",
		'137' => "VICHUQUEN",
		'35' => "VICUNA",
		'384' => "BOLLENAR",
		'437' => "AHUI",
		'438' => "AIQUINA",
		'439' => "ALGARROBAL",
		'294' => "TORRES DEL PAINE",
		'446' => "BAHIA MURTA",
		'150' => "HUALQUI",
		'441' => "ALICAHUE",
		'448' => "BAQUEDANO",
		'130' => "HUALANE",
		'492' => "COBIJA",
		'388' => "CODIGUA",
		'494' => "CODPA",
		'472' => "CAREN",
		'496' => "COLIUMO",
		'152' => "PENCO",
		'469' => "CAQUENA",
		'497' => "COLLACAGUA",
		'499' => "CONAY",
		'500' => "COSAPILLA",
		'501' => "COYA",
		'503' => "CULENAR",
		'504' => "CUMPEO",
		'505' => "CUNACO",
		'506' => "CUNCUMEN",
		'508' => "CURINANCO",
		'510' => "DEGAN",
		'511' => "DICHATO",
		'509' => "CUYA",
		'513' => "DUAO",
		'391' => "EL CANELO",
		'470' => "CARAMPANGUE",
		'471' => "CARELMAPU",
		'386' => "CHICUREO",
		'401' => "CANCOSA",
		'482' => "CHANARAL ALTO",
		'483' => "CHANARAL DE CAREN",
		'486' => "CHEPU",
		'412' => "CURAUMA",
		'487' => "CHERCHENCO",
		'467' => "CANTO DE AGUA",
		'484' => "CHARRUA",
		'562' => "LA HAUYCA",
		'488' => "CHILLEPIN",
		'485' => "CHAUQUEN",
		'174' => "SAN ROSENDO",
		'529' => "ENTRE LAGOS",
		'530' => "ESQUINA",
		'524' => "EL SAUCE",
		'176' => "TUCAPEL",
		'532' => "FARELLONES",
		'534' => "GUADAL",
		'535' => "GUALLECO",
		'552' => "HUINTIL",
		'538' => "GUAPILACUY",
		'541' => "HORCON",
		'542' => "HORCON IV",
		'518' => "EL MANZANO",
		'550' => "HUEPIL",
		'544' => "HOSPITAL",
		'545' => "HUALPENCILLO",
		'547' => "HUELDEN",
		'548' => "HUELLAHUE",
		'551' => "HUILLINCO",
		'553' => "ICALMA",
		'554' => "ILOCA",
		'521' => "EL PAICO",
		'556' => "ISLA TEJA",
		'557' => "ISLUGA",
		'536' => "GUANAQUEROS",
		'561' => "LA CHIMBA",
		'558' => "ITAHUE",
		'368' => "EL INGENIO",
		'563' => "LA JARILLA",
		'564' => "LA MARQUESA",
		'565' => "LA NEGRA",
		'566' => "LA OBRA",
		'559' => "LA ARENA",
		'523' => "EL PENON",
		'525' => "EL TABITO",
		'115' => "SANTA CRUZ",
		'579' => "LAS CRUCES",
		'581' => "LAS DUNAS",
		'573' => "LAGUNA VERDE",
		'584' => "LAS TACAS",
		'585' => "LAS TRANCAS",
		'24' => "CHANARAL",
		'587' => "LASANA",
		'588' => "LECHAGUA",
		'589' => "LEYDA",
		'590' => "LICANRAY",
		'591' => "LIMARI",
		'592' => "LINAO",
		'594' => "LIRIMA",
		'595' => "LIRQUEN",
		'396' => "LO CHACON",
		'597' => "LLICO",
		'599' => "LO MIRANDA",
		'570' => "LA TAPERA",
		'600' => "LO VALDIVIA",
		'603' => "LOS HORCONES",
		'604' => "LOS HORNOS",
		'576' => "LARAQUETE",
		'605' => "LOS LAURELES",
		'608' => "LOS MOLLES",
		'609' => "LOS NICHES",
		'610' => "LOS OLIVOS",
		'611' => "MAICOLPUE",
		'645' => "PAN DE AZUCAR",
		'614' => "MANAO",
		'370' => "LAGUNA ACULEO",
		'582' => "LAS NIEVES",
		'571' => "LA TIRANA",
		'426' => "LAS CARDAS SUR",
		'372' => "LINDEROS",
		'186' => "NINHUE",
		'628' => "MONTE AYMOND",
		'629' => "MONTE GRANDE",
		'631' => "MORRILLOS",
		'636' => "NIPAS",
		'638' => "NIRIVILO",
		'615' => "MANDINGA",
		'640' => "NUEVA BRAUNAU",
		'641' => "PACHAMA",
		'643' => "PALOMAR",
		'642' => "PAIPOTE",
		'646' => "PANGAL",
		'647' => "PANIMAVIDA",
		'648' => "PAPOSO",
		'621' => "MELINKA",
		'650' => "PARGUA",
		'651' => "PAULDEO",
		'652' => "PEDREGAL",
		'654' => "PENABLANCA",
		'655' => "PETROHUE",
		'656' => "PICHASCA",
		'657' => "PICHI PELLUCO",
		'658' => "PICHICUY",
		'661' => "PINGUERAL",
		'662' => "PISCO ELQUI",
		'663' => "POCONCHILE",
		'618' => "MATANZAS",
		'664' => "POLCURA",
		'644' => "PALQUIAL",
		'622' => "MINAS DEL PRADO",
		'635' => "NIEBLA",
		'380' => "NOS",
		'625' => "MOCHA",
		'189' => "PINTO",
		'383' => "ALTO JAHUEL",
		'672' => "PUENTE QUILO",
		'714' => "ROSARIO",
		'676' => "PUERTO BERTRAND",
		'675' => "PUERTO ALDEA",
		'671' => "PUENTE NEGRO",
		'240' => "LA UNION",
		'673' => "PUERTECILLO",
		'522' => "EL PALQUI",
		'682' => "PUERTO WILLIAMS",
		'677' => "PUERTO BORIES",
		'679' => "PUERTO TORO",
		'716' => "RUCAPEQUEN",
		'705' => "RAPEL",
		'669' => "PUEBLO SECO",
		'706' => "RAYENCURA",
		'668' => "PUCATRIHUE",
		'713' => "ROBLE HUACHO",
		'707' => "RECOLETA IV",
		'708' => "RIHUE",
		'709' => "RINCONADA DE GUZMAN",
		'710' => "RINCONADA DE SILVA",
		'711' => "RINIHUE",
		'218' => "VILCUN",
		'68' => "ALGARROBO",
		'107' => "CHEPICA",
		'190' => "PORTEZUELO",
		'392' => "EL MELOCOTON",
		'192' => "QUIRIHUE",
		'759' => "VILLA SANTA LUCIA",
		'369' => "HUELQUEN",
		'377' => "MALLOCO",
		'159' => "ARAUCO",
		'575' => "LAJAS BLANCAS",
		'724' => "SAN PEDRO QUINTA REGION",
		'731' => "SOCOROMA",
		'408' => "SOTOCA",
		'763' => "ZEMITA",
		'733' => "SORA",
		'734' => "SOTAQUI",
		'404' => "NAVIDAD",
		'48' => "JUAN FERNANDEZ",
		'756' => "VILLA MERCEDES",
		'270' => "CHAITEN",
		'719' => "SAN JUAN",
		'735' => "TAMBILLO",
		'737' => "TIERRAS BLANCAS",
		'736' => "TANILVORO",
		'342' => "TALAGANTE",
		'434' => "SAN VICENTE DE TAGUA TAGUA",
		'198' => "TREGUACO",
		'375' => "LONQUEN",
		'172' => "QUILACO",
		'117' => "CONSTITUCION",
		'118' => "CUREPTO",
		'69' => "CARTAGENA",
		'108' => "CHIMBARONGO",
		'207' => "LAUTARO",
		'239' => "PANGUIPULLI",
		'329' => "SAN JOSE DE MAIPO",
		'264' => "PUERTO OCTAY",
		'155' => "TALCAHUANO",
		'23' => "TIERRA AMARILLA",
		'440' => "ALGARROBITO",
		'722' => "SAN MARCOS",
		'293' => "PUERTO NATALES",
		'79' => "QUILPUE",
		'138' => "LINARES",
		'25' => "DIEGO DE ALMAGRO",
		'310' => "LO ESPEJO",
		'318' => "PUDAHUEL",
		'740' => "TOPOCALMA",
		'208' => "LONCOCHE",
		'90' => "MACHALI",
		'389' => "CULIPRAN",
		'269' => "SAN PABLO",
		'572' => "LABRANZA",
		'367' => "ALTO EL CANELO",
		'490' => "CHOSHUENCO",
		'491' => "CIRUELOS",
		'110' => "NANCAGUA",
		'259' => "QUEILEN",
		'9' => "COLCHANE",
		'243' => "RIO BUENO",
		'105' => "PAREDONES",
		'479' => "CERRILLOS DE TAMAYA",
		'272' => "HUALAIHUE",
		'309' => "LO BARNECHEA",
		'507' => "CURANIPE",
		'481' => "CHACAO",
		'20' => "MARIA ELENA",
		'235' => "LOS LAGOS",
		'92' => "MOSTAZAL",
		'498' => "CONARIPE",
		'42' => "MONTE PATRIA",
		'549' => "HUENTELAUQUEN",
		'531' => "ESTACION PAIPOTE",
		'543' => "HORNITOS",
		'346' => "PENAFLOR",
		'330' => "COLINA",
		'255' => "CHONCHI",
		'660' => "PILLANLELBUN",
		'413' => "PUERTO CHACABUCO",
		'379' => "RUNGUE",
		'60' => "PETORCA",
		'267' => "RIO NEGRO",
		'134' => "ROMERAL",
		'723' => "SAN PEDRO DE ALCANTARA",
		'354' => "SAN FRANCISCO DE MOSTAZAL",
		'254' => "ANCUD",
		'252' => "PUERTO VARAS",
		'253' => "CASTRO",
		'175' => "SANTA BARBARA",
		'260' => "QUELLON",
		'701' => "QUIRIQUINA",
		'477' => "CAULIN",
		'96' => "QUINTA DE TILCOCO",
		'520' => "EL MOLLE",
		'526' => "EL TAMBO",
		'284' => "PUNTA ARENAS",
		'567' => "LA PARVA",
		'442' => "ALTOVALSOL",
		'476' => "CATAPILCO",
		'480' => "CERRO SOMBRERO",
		'665' => "POPETA",
		'519' => "EL MELON",
		'475' => "CASPANA",
		'394' => "GUAYACAN",
		'578' => "LAS BREAS",
		'580' => "LAS DICHAS",
		'593' => "LIQUINE",
		'601' => "LONGOVILO",
		'51' => "VINA DEL MAR",
		'365' => "CAJON DEL MAIPO",
		'436' => "AGUA BUENA",
		'456' => "CACHAGUA",
		'489' => "CHOLGUAN",
		'495' => "COIHUE",
		'502' => "COZ COZ",
		'515' => "EL CARMEN RENGO",
		'514' => "EL BELLOTO",
		'528' => "ENSENADA",
		'533' => "GABRIELA MISTRAL",
		'546' => "HUAMALATA",
		'560' => "LA CEBADA",
		'474' => "CARRIZAL BAJO",
		'574' => "LAGUNILLAS",
		'586' => "LAS VENTANAS",
		'598' => "LLIFEN",
		'607' => "LOS MAITENES",
		'602' => "LONTUE",
		'627' => "MONTE AGUILA",
		'632' => "NAHUELTORO",
		'649' => "PARCELA EL CARMEN",
		'659' => "PICHIDANGUI",
		'637' => "NIREHUAO",
		'712' => "RININAHUE",
		'732' => "SOCOS",
		'170' => "NACIMIENTO",
		'382' => "VALDIVIA DE PAINE",
		'216' => "TEODORO SCHMIDT",
		'596' => "LLANOS DE GUANTA",
		'527' => "EL TANGUE",
		'613' => "MAMINA",
		'144' => "VILLA ALEGRE",
		'32' => "ANDACOLLO",
		'537' => "GUANGUALI",
		'577' => "LARMAHUE",
		'749' => "VALLE NEVADO",
		'721' => "SAN MANUEL",
		'751' => "VEGAS DE ITATA",
		'750' => "VALLE SIMPSON",
		'752' => "VILLA ALHUE",
		'754' => "VILLA CERRO CASTILLO",
		'755' => "VILLA MANIHUALES",
		'757' => "VILLA ORTEGA",
		'626' => "MOLINOS",
		'630' => "MONTENEGRO",
		'653' => "PELEQUEN",
		'741' => "TOTORALILLO",
		'307' => "LA REINA",
		'266' => "PUYEHUE",
		'421' => "MAITENCILLO",
		'678' => "PUERTO DOMINGUEZ",
		'688' => "PUNTA LAVAPIE",
		'697' => "QUILIMARI",
		'747' => "TUBUL",
		'195' => "SAN FABIAN",
		'153' => "SAN PEDRO DE LA PAZ",
		'569' => "LA RUFINA",
		'261' => "QUEMCHI",
		'257' => "DALCAHUE",
		'184' => "CHILLAN VIEJO",
		'753' => "VILLA AMENGUAL",
		'715' => "RUCA RAQUI (SAAVEDRA)",
		'123' => "RIO CLARO",
		'251' => "MAULLIN",
		'14' => "SIERRA GORDA",
		'764' => "FUERTE BAQUEDANO",
		'126' => "CAUQUENES",
		'317' => "PROVIDENCIA",
		'211' => "PADRE LAS CASAS",
		'328' => "PIRQUE",
		'623' => "MINCHA",
		'624' => "MININCO",
		'327' => "PUENTE ALTO",
		'326' => "VITACURA",
		'296' => "CERRILLOS",
		'339' => "CURACAVI",
		'291' => "PRIMAVERA",
		'478' => "CAYUCUPIL",
		'606' => "LOS LINGUES",
		'639' => "NUEVA ALDEA",
		'699' => "QUINCHAMALI",
		'633' => "NAL",
		'616' => "MARBELLA",
		'357' => "OLIVAR ALTO",
		'619' => "MECHAICO",
		'397' => "POLPAICO",
		'690' => "PUYUHUAPI",
		'680' => "PUERTO TRANQUILO",
		'681' => "PUERTO VELERO",
		'684' => "PUNTA CORONA",
		'666' => "PORTILLO",
		'683' => "PUNTA COLORADA",
		'692' => "QUELON",
		'685' => "PUNTA DE PARRA",
		'686' => "PUNTA DE TRALCA",
		'687' => "PUNTA DELGADA",
		'689' => "PUNUCAPA",
		'728' => "SECTOR LA PENA",
		'691' => "QUEBRADA DE TALCA",
		'693' => "QUEPE",
		'670' => "PUELO",
		'694' => "QUETALMAHUE",
		'319' => "QUILICURA",
		'695' => "QUEULE",
		'696' => "QUILCHE",
		'698' => "QUILLAGUA",
		'700' => "QUINTAY",
		'702' => "RAFAEL",
		'703' => "RAMADILLAS",
		'704' => "RANGUELMO",
		'725' => "SAN SEBASTIAN",
		'726' => "SANTA CLARA",
		'275' => "LAGO VERDE",
		'727' => "SANTA ROSA DE CHENA",
		'729' => "SEWELL",
		'555' => "ISLA NEGRA",
		'674' => "PUERTO AGUIRRE",
		'742' => "TREGUALEMU",
		'743' => "TREHUACO",
		'744' => "TROVOLHUE",
		'745' => "TRUMAO",
		'717' => "SALADILLO",
		'746' => "TRUPAN",
		'748' => "TULAHUEN",
		'720' => "SAN JULIAN",
		'718' => "SAN ALFONSO",
		'762' => "YUSTE",
		'223' => "CURACAUTIN",
		'231' => "VICTORIA",
		'348' => "EL SALVADOR",
		'374' => "LOMAS DE LO AGUIRRE",
		'493' => "CODELCO RADOMIRO TOMIC",
		'512' => "DOMEYKO",
		'540' => "HACIENDA LOS ANDES",
		'30' => "LA SERENA",
		'395' => "JUNCAL",
		'612' => "MALALCAHUELLO",
		'417' => "RAUQUEN",
		'335' => "CALERA DE TANGO",
		'210' => "NUEVA IMPERIAL",
		'213' => "PITRUFQUEN",
		'43' => "PUNITAQUI",
		'458' => "CAIMANES",
		'583' => "LAS RAMADAS DE TULAHUEN",
		'427' => "CABO DE HORNOS",
		'314' => "NUNOA",
		'324' => "SAN MIGUEL",
		'312' => "MACUL",
		'315' => "PEDRO AGUIRRE CERDA",
		'333' => "SAN BERNARDO",
		'316' => "PENALOLEN",
		'304' => "LA FLORIDA",
		'298' => "CONCHALI",
		'302' => "INDEPENDENCIA",
		'299' => "EL BOSQUE",
		'323' => "SAN JOAQUIN",
		'321' => "RECOLETA",
		'320' => "QUINTA NORMAL",
		'297' => "CERRO NAVIA",
		'322' => "RENCA",
		'305' => "LA GRANJA",
		'300' => "ESTACION CENTRAL",
		'306' => "LA PINTANA",
		'325' => "SAN RAMON",
		'301' => "HUECHURABA",
		'311' => "LO PRADO",
		'313' => "MAIPU",
		'303' => "LA CISTERNA",
		'308' => "LAS CONDES",
		'295' => "SANTIAGO CENTRO",
	);
	
	return $states;
}

function cambio_campos_checkout( $fields ) {
	
	unset($fields['billing']['billing_postcode']);
	unset($fields['shipping']['shipping_postcode']);
	
	$fields['billing']['billing_state']['label']= 'Comunas'; 
	$fields['shipping']['shipping_state']['label']= 'Comunas'; 
	
	$fields['billing']['billing_address_1']['class'] = array('form-row-first');
	$fields['shipping']['shipping_address_1']['class'] = array('form-row-first');      
	
	return $fields;
}
function shipit_woocommerce_tip(){
	?>
	<script type="text/javascript">
	jQuery( document ).ready(function( $ ) {
		jQuery('label[for="billing_state"]').text('Comunas');
		$('#billing_state').change(function(){
			jQuery('body').trigger('update_checkout');
		});
	});
	</script>
	<?php
}
add_filter( 'woocommerce_order_formatted_billing_address' , 'shipit_admin_default_billing_address_fields', 10, 2 );
 
function shipit_admin_default_billing_address_fields( $fields, $order ) {
$fields['billing_houseno'] = get_post_meta( $order->get_id(), '_billing_houseno', true );
return $fields;
}
add_filter( 'woocommerce_order_formatted_shipping_address' , 'shipit_admin_default_shipping_address_fields', 10, 2 );
 
function shipit_admin_default_shipping_address_fields( $fields, $order ) {
$fields['shipping_houseno'] = get_post_meta( $order->get_id(), '_shipping_houseno', true );
return $fields;
}
add_filter( 'woocommerce_formatted_address_replacements', 'shipit_add_new_replacement_fields',10,2 );
 
function shipit_add_new_replacement_fields( $replacements, $address ) {
$replacements['{billing_houseno}'] = isset($address['billing_houseno']) ? $address['billing_houseno'] : '';
$replacements['{shipping_houseno}'] = isset($address['shipping_houseno']) ? $address['shipping_houseno'] : '';
return $replacements;
}
add_filter( 'woocommerce_localisation_address_formats', 'shipit_admin_new_address_formats' );
 
function shipit_admin_new_address_formats( $formats ) {
$formats['CL'] = "{name_upper}\n{company_upper}\n{address_1_upper}\n{billing_houseno}\n{shipping_houseno}\n{address_2_upper}\n{city_upper}\n{state_upper}\n{postcode_upper}\n{country}";
return $formats;
}

function shipit_houseno_display_order_data_in_admin( $order ){  ?>
    <div class="order_data_column">

        <h4><?php _e( 'Campos Shipit', 'woocommerce' ); ?><a href="#" class="edit_address"><?php _e( 'Edit', 'woocommerce' ); ?></a></h4>
        <div class="address">
        <?php 
            echo '<p><strong>' . __( 'Numero de vivienda Facturacion' ) . ':</strong>' . $order->get_meta( '_billing_houseno' ) . '</p>';
            echo '<p><strong>' . __( 'Numero de vivienda Envio' ) . ':</strong>' . $order->get_meta( '_shipping_houseno' ) . '</p>'; ?>
        </div>
        <div class="edit_address">
            <?php woocommerce_wp_text_input( array( 'id' => '_billing_houseno', 'label' => __( 'Numero de vivienda' ), 'wrapper_class' => '_billing_houseno' ) ); ?>
            <?php woocommerce_wp_text_input( array( 'id' => '_shipping_houseno', 'label' => __( 'Numero de vivienda Envio' ), 'wrapper_class' => '_shipping_houseno' ) ); ?>
        </div>
    </div>
<?php }
add_action( 'woocommerce_admin_order_data_after_order_details', 'shipit_houseno_display_order_data_in_admin' );

function shipit_houseno_save_extra_details( $order_id, $post ){
    $order = wc_get_order( $order_id );
    $order->update_meta_data( '_billing_houseno', wc_clean( $_POST[ '_billing_houseno' ] ) );
    $order->update_meta_data( '_shipping_houseno', wc_clean( $_POST[ '_shipping_houseno' ] ) );
    $order->save_meta_data();
}
add_action( 'woocommerce_process_shop_order_meta', 'shipit_houseno_save_extra_details', 45, 2 );

add_action( 'wp_head', 'shipit_woocommerce_tip' );
add_filter('woocommerce_checkout_fields' , 'cambio_campos_checkout');
add_filter('woocommerce_states', 'comunas_de_chile');
?>